spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snpuser?serverTimezone=Asia/Seoul
    username: snpadmin
    password: snp123!@#
  properties:
    hibernate:
      format_sql : true
  logging:
    level:
      org.hibernate.SQL: debug
  jpa:
    hibernate:
      ddl-auto: none


