server:
  port: 8887

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: snp-config-server

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjw1995-snp-org/CONFIG-SERVER.git
          search-paths: src/main/resources/**
          default-label: main
          username: kjw1995
          password: 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
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

jwt:
  secret-key: c29jaWFsLW5ldHdvcmstcHJvamVjdC11c2VyLXNlcnZpY2Utand0LXNlY3JldC1rZXktY3JlYXRlLWJ5LWtqdzE5OTU= #social-network-project-user-service-jwt-secret-key-create-by-kjw1995
  access-token-expiry-seconds: 21600 #6시간
  refresh-token-expiry-seconds: 604800 #1주일