server:
  port: 8887

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjw1995-snp-org/CONFIG-SERVER.git
          search-paths: src/main/resources/**
          default-label: main
          username: kjw1995
#          all_access_token
          password: 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
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true