server:
  port: 8887

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: snp-config-server

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjw1995-snp-org/CONFIG-SERVER.git
          search-paths: src/main/resources/**
          default-label: main
          username: kjw1995
#          all_access_token
          password: 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
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true