server:
  port: 8887

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kjw1995-snp-org/snp-configserver.git
          search-paths: src/main/resources/**
          default-label: main
          username: kjw1995
#          all_access_token
          password: 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
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true