server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: src/main/resources/**
          default-label: main
          username: rohawell@daum.net
          password: vkfksakswkd2@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true