spring:
  mvc:
    static:
      path:
        pattern: /static/**
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

server:
  tomcat:
    threads:
      max: 1000
      min-spare: 100
    max-connections: 8192
    accept-count: 200
    connection-timeout: 180000
  port: 8889

jwt:
  secret-key: c29jaWFsLW5ldHdvcmstcHJvamVjdC11c2VyLXNlcnZpY2Utand0LXNlY3JldC1rZXktY3JlYXRlLWJ5LWtqdzE5OTU= #social-network-project-user-service-jwt-secret-key-create-by-kjw1995