logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: snp-comment-service

management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8891